sudo: required
dist: bionic
language: go
go:
    - "1.9"
    - "1.10"	
install: 
    - go get -u github.com/golang/dep/cmd/dep
    - dep ensure
    - go test -v ./pkg/locker
    - go test -v ./cmd/locker
script: 
    - go build ./cmd/locker/
